/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
Lista de paquetes:
 */
package josebailon.clientecorreo.vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Properties;
import josebailon.clientecorreo.controlador.Controlador;

/**
 *
 * @author Jose Javier BO
 */
public class Ventana extends javax.swing.JFrame implements ActionListener{
    Controlador control;
    
    
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        eventos();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panelBotonera = new javax.swing.JPanel();
        btnConfiguracion = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelCentral = new javax.swing.JSplitPane();
        scrollLista = new javax.swing.JScrollPane();
        listaCorreos = new javax.swing.JList<>();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBotonera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnConfiguracion.setText("Configuración");
        btnConfiguracion.setActionCommand("abrirConfiguracion");
        panelBotonera.add(btnConfiguracion);

        btnActualizar.setText("Actualizar");
        btnActualizar.setActionCommand("actualizarCorreos");
        panelBotonera.add(btnActualizar);

        btnCrear.setText("Crear");
        btnCrear.setActionCommand("crearCorreo");
        panelBotonera.add(btnCrear);

        btnSalir.setText("Salir");
        btnSalir.setActionCommand("salir");
        panelBotonera.add(btnSalir);

        panelCentral.setDividerSize(10);

        listaCorreos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1\\npaso", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollLista.setViewportView(listaCorreos);

        panelCentral.setLeftComponent(scrollLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCentral)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBotonera, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JList<String> listaCorreos;
    private javax.swing.JPanel panelBotonera;
    private javax.swing.JSplitPane panelCentral;
    private javax.swing.JScrollPane scrollLista;
    // End of variables declaration//GEN-END:variables

    /**
     * Define el controlador
     * @param c  El controlador
     */
    public void setControlador(Controlador c) {
        control=c;
    }

 

    private void eventos() {
        btnConfiguracion.addActionListener(this);
        btnActualizar.addActionListener(this);
        btnCrear.addActionListener(this);
        btnSalir.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        String ac = e.getActionCommand();
        switch (ac) {
            case "abrirConfiguracion" -> pedirConfiguracion();
            case "actualizarCorreos" -> actualizarCorreos();
            case "crearCorreo" -> crearCorreo();
            case "salir" -> salir();
            default -> {
            }

        }
    }

    public void pedirConfiguracion() {
        Properties config = control.getConfig();
        
        DConfiguracion d = new DConfiguracion(this, config);
        d.setVisible(true);

    }

    private void actualizarCorreos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void crearCorreo() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void salir() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
